apiVersion: com.afan104/v1
kind: RotatingSecret
metadata:
  name: rotating-secret
spec:
  secretName: app-secret # to match deployments envFrom so status-app can look at it
  length: 15
  rotationIntervalSeconds: 30
