apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rotating-secret-operator
rules:
  - apiGroups: ["com.afan104"]
    resources: ["rotatingsecrets"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["com.afan104"]
    resources: ["rotatingsecrets/status"]
    verbs: ["get", "update", "patch"]
  - apiGroups: [""] # secrets is core k8s type so no apigroup
    resources: ["secrets"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
